FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm i -g pnpm
COPY . /app
WORKDIR /app


FROM base AS build
RUN --mount=type=cache,id=s/232c385e-bb59-44e9-ad3a-51a7f243e5f7-/pnpm/store,target=/pnpm/store pnpm install --frozen-lockfile --filter api...
RUN pnpm turbo build --filter api

FROM base
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/apps/api/.output /app/.output
CMD [ "node", "/app/.output/server/index.mjs" ]
