FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm i -g pnpm
COPY . /app
WORKDIR /app


FROM base AS build
ARG PUBLIC_RSUITE_CLIENT_ID
RUN --mount=type=cache,id=s/7ac41127-9aa2-45ea-83d7-c72886ab5839-/pnpm/store,target=/pnpm/store pnpm install --frozen-lockfile --filter app...
RUN pnpm turbo build --filter app

FROM caddy:alpine
COPY --from=base /app/apps/app/caddy/Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/apps/app/.output/public /var/www
