FROM node:20-slim AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm i -g pnpm
COPY . /app
WORKDIR /app


FROM base AS build
ARG PUBLIC_RSUITE_CLIENT_ID
RUN --mount=type=cache,id=s/a214cd7e-89b6-4d02-ac36-59b97c9749cd-/pnpm/store,target=/pnpm/store pnpm install --frozen-lockfile --filter app...
RUN pnpm turbo build --filter app

FROM caddy:alpine
COPY --from=base /app/apps/app/caddy/Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/apps/app/.output/public /var/www
