[build]
  publish = "apps/landing/dist"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF apps/landing packages/*"
  command = "pnpm turbo build --filter landing"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
