[build]
  publish = "apps/landing/dist"
  command = "pnpm turbo build --filter landing"
[build.processing.html]
  pretty_urls = false
[[headers]]
  for = "/_astro/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
